version: '3.8'

services:
  database:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWD}
      MYSQL_DATABASE: ${MYSQL_DB}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWD}
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - my_network

  adminer:
    image: adminer:latest
    ports:
      - 8080:8080
    networks:
      - my_network

volumes:
  db_data:

networks:
  my_network:

name: ${PROJECT_NAME}
