---
- name: Configure remote host for Docker
  hosts: all
  become: true
  vars:
    new_hostname: "my-docker-host"  # Replace with your desired hostname
    docker_user: "dockeruser"
    docker_repo: "https://github.com/3210snoop3210/docker-compose.git"  # Replace with your repository URL
    docker_compose_file: "Docker_compose_sql.yaml"  # Replace with your Docker Compose file name

  tasks:

    # Change hostname
    - name: Set new hostname
      ansible.builtin.hostname:
        name: "{{ new_hostname }}"

    # Set timezone to Kyiv
    - name: Set timezone to Europe/Kiev
      community.general.timezone:
        name: Europe/Kiev

    # Create Docker user
    - name: Create Docker user
      user:
        name: "{{ docker_user }}"
        shell: /bin/bash
        createhome: yes

    # Add docker repos
    - name: Add Docker repos
      shell:  yum-config-manager --add-repo=https://download.docker.com/linux/centos/docker-ce.repo
      become_user: root

    # Install Docker and Docker Compose
    - name: Install Docker
      yum:
        name:
        - docker-ce 
        - docker-ce-cli
        - containerd.io
        - docker-buildx-plugin
        - docker-compose-plugin
        state: latest
      become_user: root

    # Configure Docker user to use Docker without sudo
    - name: Add Docker user to docker group
      usermod:
        name: "{{ docker_user }}"
        groups: docker

    # Open ports 22, 80, and 443
    - name: Open firewall ports
      ansible.builtin.firewalld:
        rule: allow
        port: "{{ item }}"
      with_items:
        - 22
        - 80
        - 443

    # Clone Docker Compose repository
    - name: Clone Docker Compose repository
      git:
        repo: "{{ docker_repo }}"
        dest: /home/{{ docker_user }}/{{ docker_repo | basename }}"
        update: yes
      become_user: "{{ docker_user }}"

    # Run Docker Compose file
    - name: Run Docker Compose file
      become_user: "{{ docker_user }}"
      shell: docker compose up -f /home/{{ docker_user }}/{{ docker_repo | basename }}/{{ docker_compose_file }} -d
      become_user: "{{ docker_user }}"

    # Enable Docker Compose to start on boot
    - name: Enable Docker Compose to start on boot
      systemd:
        name: docker-compose@{{ docker_repo | basename }}
        enabled: yes
        user: "{{ docker_user }}"
        command: docker compose up -f /home/{{ docker_user }}/{{ docker_repo | basename }}/{{ docker_compose_file }} -d
      become_user: root
